// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SotomayorMateo_Progreso1.Data;

#nullable disable

namespace SotomayorMateo_Progreso1.Migrations
{
    [DbContext(typeof(SotomayorMateo_Progreso1Context))]
    [Migration("20241029135015_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SotomayorMateo_Progreso1.Models.Celular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerezId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Celular");
                });

            modelBuilder.Entity("SotomayorMateo_Progreso1.Models.Sotomayor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CelularId")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Ingresos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CelularId")
                        .IsUnique()
                        .HasFilter("[CelularId] IS NOT NULL");

                    b.ToTable("Sotomayor");
                });

            modelBuilder.Entity("SotomayorMateo_Progreso1.Models.Sotomayor", b =>
                {
                    b.HasOne("SotomayorMateo_Progreso1.Models.Celular", "Celular")
                        .WithOne("Propietario")
                        .HasForeignKey("SotomayorMateo_Progreso1.Models.Sotomayor", "CelularId");

                    b.Navigation("Celular");
                });

            modelBuilder.Entity("SotomayorMateo_Progreso1.Models.Celular", b =>
                {
                    b.Navigation("Propietario")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
